# Docker Compose version
version: "3"

# Define services (containers to be created)
services:
  # Service name: pingvin-share
  pingvin-share:
    # Name of the service
    container_name: pingvin-share

    # Image to use for this container
    image: stonith404/pingvin-share:latest

    labels:
      icon: "https://github.com/GeorgeLeithead/CasaOs_Resources/blob/main/PingVin/pingvin.png?raw=true"

    ports:
      # Port mapping between host and container
      - 3000:3000/tcp # Web UI HTTP

    environment:
      # Environment variables
      TZ: "Eurpoe/London" # Time Zone; Update this to your time zone

    volumes:
      # Defines volume mounts for the service
      - type: bind
        source: /mnt/Storage1_nvme0n1p1/DATA/AppData/pingvin-share/data
        target: /opt/app/backend/data
      - type: bind
        source: /mnt/Storage1_nvme0n1p1/DATA/AppData/pingvin-share/images
        target: /opt/app/frontend/public/img

    # Restart policy for the container when it exits
    restart: unless-stopped      