# Docker Compose version
version: "3.8"

# Define services (containers to be created)
services:
  # Service name: cloudflared
  cloudflared:
    # Name of the container instance
    container_name: cloudflared

    # Image to use for this container
    image: wisdomsky/cloudflared-web:latest

    # Expose and map ports (host:container)
    ports:
      - "14333:14333/tcp" # Token-Setup WebUI

    # Environment variables
    environment: []

    volumes:
      # Defines volume mounts for the service
      - type: bind
        source: /mnt/Storage1_nvme0n1p1/DATA/AppData/casaos-cloudflared/config # Default is /DATA/AppData/casaos-cloudflared/config
        target: /config # Contains config file where cloudflare token is stored.

    # Restart policy for the container when it exits
    restart: unless-stopped

    # Network mode
    network_mode: host