# Docker Compose version
version: "3.8"

# Define services (containers to be created)
services:
  # Service name: jellyfin
  jellyfin:
    # Name of the service
    container_name: jellyfin

    # Image to use for this container
    image: linuxserver/jellyfin:latest

    labels:
      icon: https://github.com/GeorgeLeithead/CasaOs_Resources/blob/main/jellyfin/jellyfin.png?raw=true

    ports:
      # Port mapping between host and container
      - 8920:8920/tcp # DNS (TCP)
      - 1900:1900/tcp # DNS (TCP)
      - 7359:7359/tcp # DNS (TCP)
      - 8096:8096/tcp # Web UI HTTP

    environment:
      # Environment variables
      - TZ=Eurpoe/London # Time Zone; Update this to your time zone
      - PGID=1000
      - PUID=1000

    volumes:
      # Defines volume mounts for the service
      - type: bind
        source: /mnt/Storage1_nvme0n1p1/DATA/AppData/Jellyfin/config # Default is /DATA/AppData/JellyFin/config
        target: /config
      - type: bind
        source: /opt/vc/lib
        target: /opt/vc/lib
      - type: bind
        source: /mnt/Storage1_nvme0n1p1/Media # Default is /Media
        target: /Media

    # Restart policy for the container when it exits
    restart: always