# Docker Compose version
version: "3.8"

# Define services (containers to be created)
services:
  # Service name: sqlserver
  sqlserver:
    # Name of the container instance
    container_name: sqlserver

    command:
      - /opt/mssql/bin/sqlservr

    # Image to use for this container
    # Use the specified version of the MS SQL Server 2022 image
    image: mcr.microsoft.com/mssql/server:2022-latest

    labels:
      icon: https://github.com/GeorgeLeithead/CasaOs_Resources/blob/main/sqlserver/sqlserver.png?raw=true

    # Expose and map ports (host:container)
    ports:
      - 1433:1433/tcp

    # Environment variables
    environment:
      - ACCEPT_EULA=Y
      - CONFIG_EDGE_BUILD=
      - MSSQL_RPC_PORT=135
      - MSSQL_SA_PASSWORD=sa # Change this to your preferred password
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    # Mount volumes for persistent data
    volumes:
      - type: bind
        source: /mnt/Storage1_nvme0n1p1/DATA/AppData/mssql
        target: /var/opt/mssql

    # Restart policy for the container when it exits
    restart: unless-stopped